-- Generated by Mocodo 4.2.12

CREATE TABLE COMMENTER (
  PRIMARY KEY (id_admin, id_ticket),
  id_admin            VARCHAR(42) NOT NULL,
  id_ticket           VARCHAR(42) NOT NULL,
  date_commentaire    VARCHAR(42),
  contenu_commentaire VARCHAR(42)
);

CREATE TABLE Evenements (
  PRIMARY KEY (id_evenement),
  id_evenement   VARCHAR(42) NOT NULL,
  date_evenement VARCHAR(42),
  nom_evenement  VARCHAR(42),
  type_evenement VARCHAR(42)
);

CREATE TABLE Grades (
  PRIMARY KEY (id_grade),
  id_grade  VARCHAR(42) NOT NULL,
  nom_grade VARCHAR(42)
);

CREATE TABLE Joueurs (
  PRIMARY KEY (id_joueur),
  id_joueur     VARCHAR(42) NOT NULL,
  nom_joueur    VARCHAR(42),
  prenom_joueur VARCHAR(42),
  pseudo_joueur VARCHAR(42),
  email_joueur  VARCHAR(42),
  mdp_joueur    VARCHAR(42),
  id_grade      VARCHAR(42) NOT NULL
);

CREATE TABLE Messages (
  PRIMARY KEY (id_message),
  id_message      VARCHAR(42) NOT NULL,
  date_message    VARCHAR(42),
  nom_message     VARCHAR(42),
  contenu_message VARCHAR(42),
  id_joueur       VARCHAR(42) NOT NULL
);

CREATE TABLE ORGANISER (
  PRIMARY KEY (id_admin, id_evenement),
  id_admin     VARCHAR(42) NOT NULL,
  id_evenement VARCHAR(42) NOT NULL
);

CREATE TABLE Personnages (
  PRIMARY KEY (id_perso),
  id_perso     VARCHAR(42) NOT NULL,
  nom_perso    VARCHAR(42),
  classe_perso VARCHAR(42),
  race_perso   VARCHAR(42),
  id_joueur    VARCHAR(42) NOT NULL
);

CREATE TABLE POSTULER (
  PRIMARY KEY (id_perso, id_evenement),
  id_perso     VARCHAR(42) NOT NULL,
  id_evenement VARCHAR(42) NOT NULL
);

CREATE TABLE RECEVOIR (
  PRIMARY KEY (id_joueur, id_message),
  id_joueur  VARCHAR(42) NOT NULL,
  id_message VARCHAR(42) NOT NULL
);

CREATE TABLE REPARTIR (
  PRIMARY KEY (id_admin, id_grade),
  id_admin VARCHAR(42) NOT NULL,
  id_grade VARCHAR(42) NOT NULL
);

CREATE TABLE STATUER (
  PRIMARY KEY (id_admin, id_joueur),
  id_admin  VARCHAR(42) NOT NULL,
  id_joueur VARCHAR(42) NOT NULL
);

CREATE TABLE Statuts (
  PRIMARY KEY (id_statut),
  id_statut  VARCHAR(42) NOT NULL,
  nom_statut VARCHAR(42),
  id_admin   VARCHAR(42) NOT NULL
);

CREATE TABLE Tickets (
  PRIMARY KEY (id_ticket),
  id_ticket      VARCHAR(42) NOT NULL,
  date_ticket    VARCHAR(42),
  nom_ticket     VARCHAR(42),
  contenu_ticket VARCHAR(42),
  id_joueur      VARCHAR(42) NOT NULL,
  id_statut      VARCHAR(42) NOT NULL
);

ALTER TABLE COMMENTER ADD FOREIGN KEY (id_ticket) REFERENCES Tickets (id_ticket);

ALTER TABLE Joueurs ADD FOREIGN KEY (id_grade) REFERENCES Grades (id_grade);

ALTER TABLE Messages ADD FOREIGN KEY (id_joueur) REFERENCES Joueurs (id_joueur);

ALTER TABLE ORGANISER ADD FOREIGN KEY (id_evenement) REFERENCES Evenements (id_evenement);

ALTER TABLE Personnages ADD FOREIGN KEY (id_joueur) REFERENCES Joueurs (id_joueur);

ALTER TABLE POSTULER ADD FOREIGN KEY (id_evenement) REFERENCES Evenements (id_evenement);
ALTER TABLE POSTULER ADD FOREIGN KEY (id_perso) REFERENCES Personnages (id_perso);

ALTER TABLE RECEVOIR ADD FOREIGN KEY (id_message) REFERENCES Messages (id_message);
ALTER TABLE RECEVOIR ADD FOREIGN KEY (id_joueur) REFERENCES Joueurs (id_joueur);

ALTER TABLE REPARTIR ADD FOREIGN KEY (id_grade) REFERENCES Grades (id_grade);

ALTER TABLE STATUER ADD FOREIGN KEY (id_joueur) REFERENCES Joueurs (id_joueur);

ALTER TABLE Tickets ADD FOREIGN KEY (id_statut) REFERENCES Statuts (id_statut);
ALTER TABLE Tickets ADD FOREIGN KEY (id_joueur) REFERENCES Joueurs (id_joueur);
